# Generated automatically from Make-in by configure.
# Makefile for program source directory in GNU NLS utilities package.
# Copyright (C) 1995, 1996, 1997 by Ulrich Drepper <drepper@gnu.ai.mit.edu>
#
# This file file be copied and used freely without restrictions.  It can
# be used in projects which are not available under the GNU Public License
# but which still want to provide support for the GNU gettext functionality.
# Please note that the actual code is *not* freely available.

PACKAGE = binutils
VERSION = 2.14

SHELL = /bin/sh


srcdir = /cs161/cs161-binutils-1.4/./binutils-2.14/binutils/po
top_srcdir = /cs161/cs161-binutils-1.4/./binutils-2.14/binutils
VPATH = /cs161/cs161-binutils-1.4/./binutils-2.14/binutils/po

prefix = /root/cs161/tools
exec_prefix = ${prefix}
datadir = $(prefix)/share
localedir = $(datadir)/locale
gnulocaledir = $(prefix)/share/locale
gettextsrcdir = $(prefix)/share/gettext/po
subdir = po

INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
MKINSTALLDIRS = $(srcdir)/../../mkinstalldirs

CC = gcc
GENCAT = @GENCAT@
GMSGFMT = PATH=../src:$$PATH /usr/bin/msgfmt
MSGFMT = /usr/bin/msgfmt
XGETTEXT = PATH=../src:$$PATH /usr/bin/xgettext
MSGMERGE = PATH=../src:$$PATH msgmerge

DEFS = -DHAVE_CONFIG_H
CFLAGS = -g -O2
CPPFLAGS = 

INCLUDES = -I.. -I$(top_srcdir)/intl

COMPILE = $(CC) -c $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $(XCFLAGS)

SOURCES = cat-id-tbl.c
POFILES =  fr.po tr.po ja.po es.po sv.po da.po zh_CN.po
GMOFILES =  fr.gmo tr.gmo ja.gmo es.gmo sv.gmo da.gmo zh_CN.gmo
DISTFILES = ChangeLog Makefile.in.in POTFILES.in $(PACKAGE).pot \
stamp-cat-id $(POFILES) $(GMOFILES) $(SOURCES)

POTFILES = \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/addr2line.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/ar.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/arsup.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/arsup.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/binemul.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/binemul.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/bucomm.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/bucomm.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/budbg.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/budemang.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/budemang.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/coffdump.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/coffgrok.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/coffgrok.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/cxxfilt.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/debug.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/debug.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/debug.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/dlltool.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/dlltool.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/dllwrap.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/emul_aix.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/emul_vanilla.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/filemode.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/ieee.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/ieee.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/is-ranlib.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/is-strip.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/maybe-ranlib.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/maybe-strip.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/nlmconv.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/nlmconv.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/nm.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/not-ranlib.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/not-strip.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/objcopy.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/objdump.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/prdbg.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rdcoff.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rdcoff.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rddbg.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rddbg.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/readelf.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rename.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/resbin.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/rescoff.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/resrc.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/resres.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/size.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/srconv.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/stabs.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/stabs.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/strings.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/sysdump.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/version.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/windres.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/windres.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/winduni.c \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/winduni.h \
	/cs161/cs161-binutils-1.4/./binutils-2.14/binutils/wrstabs.c

CATALOGS =  fr.gmo tr.gmo ja.gmo es.gmo sv.gmo da.gmo zh_CN.gmo
CATOBJEXT = .gmo
INSTOBJEXT = .mo

.SUFFIXES:
.SUFFIXES: .c .o .po .pox .gmo .mo .msg .cat

.c.o:
	$(COMPILE) $<

.po.pox:
	$(MAKE) $(PACKAGE).pot
	$(MSGMERGE) $< $(srcdir)/$(PACKAGE).pot -o $*.pox

.po.mo:
	$(MSGFMT) -o $@ $<

.po.gmo:
	file=$(srcdir)/`echo $* | sed 's,.*/,,'`.gmo \
	  && rm -f $$file && $(GMSGFMT) -o $$file $<

.po.cat:
	sed -f ../intl/po2msg.sed < $< > $*.msg \
	  && rm -f $@ && $(GENCAT) $@ $*.msg


all: all-yes

all-yes: $(CATALOGS) # $(PACKAGE).pot
all-no:

$(srcdir)/$(PACKAGE).pot: $(POTFILES)
	$(XGETTEXT) --default-domain=$(PACKAGE) --directory=$(top_srcdir) \
	  --add-comments --keyword=_ --keyword=N_ \
	  --files-from=$(srcdir)/POTFILES.in
	rm -f $(srcdir)/$(PACKAGE).pot
	mv $(PACKAGE).po $(srcdir)/$(PACKAGE).pot

$(srcdir)/cat-id-tbl.c: stamp-cat-id; @:
$(srcdir)/stamp-cat-id: $(PACKAGE).pot
	rm -f cat-id-tbl.tmp
	sed -f ../intl/po2tbl.sed $(srcdir)/$(PACKAGE).pot \
		| sed -e "s/@PACKAGE NAME@/$(PACKAGE)/" > cat-id-tbl.tmp
	if cmp -s cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; then \
	  rm cat-id-tbl.tmp; \
	else \
	  echo cat-id-tbl.c changed; \
	  rm -f $(srcdir)/cat-id-tbl.c; \
	  mv cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; \
	fi
	cd $(srcdir) && rm -f stamp-cat-id && echo timestamp > stamp-cat-id


install: install-exec install-data
install-exec:
install-info:
install-data: install-data-yes
install-data-no: all
install-data-yes: all
	if test -r $(MKINSTALLDIRS); then \
	  $(MKINSTALLDIRS) $(datadir); \
	else \
	  $(top_srcdir)/mkinstalldirs $(datadir); \
	fi
	@catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  case "$$cat" in \
	    *.gmo) destdir=$(gnulocaledir);; \
	    *)     destdir=$(localedir);; \
	  esac; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  dir=$$destdir/$$lang/LC_MESSAGES; \
	  if test -r $(MKINSTALLDIRS); then \
	    $(MKINSTALLDIRS) $$dir; \
	  else \
	    $(top_srcdir)/mkinstalldirs $$dir; \
	  fi; \
	  if test -r $$cat; then \
	    $(INSTALL_DATA) $$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $$cat as $$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  else \
	    $(INSTALL_DATA) $(srcdir)/$$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $(srcdir)/$$cat as" \
		 "$$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  fi; \
	  if test -r $$cat.m; then \
	    $(INSTALL_DATA) $$cat.m $$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	    echo "installing $$cat.m as $$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	  else \
	    if test -r $(srcdir)/$$cat.m ; then \
	      $(INSTALL_DATA) $(srcdir)/$$cat.m \
		$$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	      echo "installing $(srcdir)/$$cat as" \
		   "$$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	    else \
	      true; \
	    fi; \
	  fi; \
	done
	if test "$(PACKAGE)" = "gettext"; then \
	  if test -r $(MKINSTALLDIRS); then \
	    $(MKINSTALLDIRS) $(gettextsrcdir); \
	  else \
	    $(top_srcdir)/mkinstalldirs $(gettextsrcdir); \
	  fi; \
	  $(INSTALL_DATA) $(srcdir)/Makefile.in.in \
			  $(gettextsrcdir)/Makefile.in.in; \
	else \
	  : ; \
	fi

# Define this as empty until I found a useful application.
installcheck:

uninstall:
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	done
	rm -f $(gettextsrcdir)/po-Makefile.in.in

check: all

cat-id-tbl.o: ../intl/libgettext.h

dvi info tags TAGS ID:

mostlyclean:
	rm -f core core.* *.pox $(PACKAGE).po *.old.po cat-id-tbl.tmp
	rm -fr *.o

clean: mostlyclean

distclean: clean
	rm -f Makefile Makefile.in POTFILES *.mo *.msg *.cat *.cat.m

maintainer-clean: distclean
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."
	rm -f $(GMOFILES)

distdir = ../$(PACKAGE)-$(VERSION)/$(subdir)
dist distdir: update-po $(DISTFILES)
	dists="$(DISTFILES)"; \
	for file in $$dists; do \
	  ln $(srcdir)/$$file $(distdir) 2> /dev/null \
	    || cp -p $(srcdir)/$$file $(distdir); \
	done

update-po: Makefile
	$(MAKE) $(PACKAGE).pot
	PATH=`pwd`/../src:$$PATH; \
	cd $(srcdir); \
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  mv $$lang.po $$lang.old.po; \
	  echo "$$lang:"; \
	  if $(MSGMERGE) $$lang.old.po $(PACKAGE).pot -o $$lang.po; then \
	    rm -f $$lang.old.po; \
	  else \
	    echo "msgmerge for $$cat failed!"; \
	    rm -f $$lang.po; \
	    mv $$lang.old.po $$lang.po; \
	  fi; \
	done

POTFILES: POTFILES.in
	( if test 'x$(srcdir)' != 'x.'; then \
	    posrcprefix='$(top_srcdir)/'; \
	  else \
	    posrcprefix="../"; \
	  fi; \
	  rm -f $@-t $@ \
	    && (sed -e '/^#/d' -e '/^[ 	]*$$/d' \
		    -e "s@.*@	$$posrcprefix& \\\\@" < $(srcdir)/$@.in \
		| sed -e '$$s/\\$$//') > $@-t \
	    && chmod a-w $@-t \
	    && mv $@-t $@ )

POTFILES.in: # ../Makefile
	cd .. && $(MAKE) po/POTFILES.in

Makefile: Make-in ../config.status POTFILES
	cd .. \
	  && CONFIG_FILES=$(subdir)/Makefile.in:$(subdir)/Make-in \
	     CONFIG_HEADERS= $(SHELL) ./config.status

# Tell versions [3.59,3.63) of GNU make not to export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
