Script started on Tue 13 Feb 2018 07:55:00 PM CST
]777;notify;Command completed;sys161 kernel]0;zdebardlebon@localhost:~/cs161]7;file://localhost.localdomain/home/zdebardlebon/cs161[?1034h[zdebardlebon@localhost cs161]$ cd ![K~/cs161/root/
]777;notify;Command completed;cd ~/cs161/root/]0;zdebardlebon@localhost:~/cs161/root]7;file://localhost.localdomain/home/zdebardlebon/cs161/root[zdebardlebon@localhost root]$ ./sys161 kernel
sys161: System/161 release 1.14, compiled Feb 13 2018 19:53:07

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 300496568 cycles (4213558k, 19u, 296282991i)
sys161: 1846 irqs 6 exns 0r/0w disk 28r/667w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 12.017481 seconds (25.005 mhz)
sys161: Elapsed virtual time: 12.019862720 seconds (25 mhz)
]777;notify;Command completed;./sys161 kernel]0;zdebardlebon@localhost:~/cs161/root]7;file://localhost.localdomain/home/zdebardlebon/cs161/root[zdebardlebon@localhost root]$ exit

Script done on Tue 13 Feb 2018 07:55:28 PM CST
